# Generated by Django 5.1.1 on 2024-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitthesis', '0010_sectionversion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sectionversion',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
