# Generated by Django 5.1.1 on 2024-10-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitthesis', '0012_alter_section_content_alter_sectionversion_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
